/*jshint esversion: 6 */
const EventEmitter = require('events');
const OPTIONS = require('./../../optionHandler/OptionHandler');
const Todo = require('./../Todo');
const activeTaskPage = require('./../activeTodoPage');




/*
Todo: an object generated by the add todo form that
includes enough information to be able to generate new habits,
projects, tasks and habits from it.
Example:
  category: ""
  categoryId: ""
  dueTo: Fri Jun 07 2019 14:43:46 GMT+0900 (Japan Standard Time) {}
  frequency: 0
  habitId: ""
  hours: "1"
  learning: false
  name: "Dame una b"
  nextTaskDate: ""
  progress: 0
  project: ""
  projectId: ""
  status: "active"
  type: "task"
  urgency: "Normal"
  user: "5cecb8ba49c45525f49f4941"
  isNewCategory: false
  isNewProject: true
 */


/**
 *
 */
module.exports = class NewTaskManager extends EventEmitter{

  constructor(model){
    super();
    model.on('newTodo', (todo) => manageTodo(todo));
  }
};

function manageTodo(todo){

  if (todo.isNewCategory){
    console.log('newCat!');
  }

  if (todo.isNewProject){
    console.log('newProj!');
  }

  if (todo.type == 'task'){
    saveActiveTaskAndDisplay(todo);
  }

}


/**
 *
 */
function saveActiveTaskAndDisplay(todo) {

  let task = new Todo();
  task.title = todo.name;
  task.dueTo = todo.dueTo;
  task.urgency = todo.urgency;
  task.hours = todo.hours;
  task.isLearning = todo.learning;
  task.categoryId = todo.categoryId;
  task.projectId = todo.projectId;
  task.progress = 0;

  let callback;
  let errorHandler;

  if (OPTIONS.checkingHabitsIsNeeded()){
    console.log('need to check habits first!');
    let today = new Date();
    OPTIONS.setLastHabitUpdate(today);

  }else{
    callback = () => {};
    errorhandler = () => {activeTaskPage.showPage();};
    OPTIONS.activeTodos.addActiveTasks([task], callback, errorHandler);
    activeTaskPage.showPageWithHightlights();
  }


}
