/*jshint esversion: 6 */
const OPTIONS = require('./../optionHandler/OptionHandler');

module.exports = class ListItemTag{
  constructor(){

  }

  /**
   * Returns a tag element with the letter "L" of learning in it
   * and the same color as the corresponding category of the todo.
   * If category id does not exist anymore, a blue color is applied
   * by default to the tag.
   */
  getLearningTag(isLearning, catId){

    if(isLearning){

      let catDeets = getCategoryDeets(catId);

      let tag;
      tag = $('<span>',{
        text: 'L',
        class: 'std_listItem_tag'});
      tag.css('background-color',catDeets.color);
      tag.css('opacity','0.75');

      return tag;
    }

  }

  getProjectTag(){

  }


  /**
   * Returns a tag element with the corresponding text and color
   * to the received category id.
   * If category id does not exist anymore, a 'Other' category
   * is generated by default.
   */
  getCategoryTag(catId){

    let catDeets = getCategoryDeets(catId);

    let tag;
    tag = $('<span>',{
      text: catDeets.title,
      class: 'std_listItem_tag'});
    tag.css('background-color',catDeets.color);

    return tag;
  }
};



function getCategoryDeets(catId) {

  let catTitle = 'Other';
  let catColor = '#263e65';

  if (catId!=''){
    let catObj = OPTIONS.categories.getCategoryById(catId);
    if (catObj != undefined){
      catTitle = catObj.title;
      catColor = catObj.color;
    }
  }

  return {title: catTitle, color: catColor};
}
